import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Counter } from "../components/Counter";
import TestFieldInput from "../components/TestFieldInput";
import * as Dialog from "@radix-ui/react-dialog";
import { Cross2Icon } from "@radix-ui/react-icons";
import React, { useEffect, useState } from "react";

interface MyData {
  // Define the properties you expect in the JSON response
  key: string;
  value: number;
}

type BulletinBoardData = {
  // Define the properties of a single row from the bulletinBoard table
  id: string;
  description: string;
  // ... add other properties based on your schema
};

type BulletinBoardArray = {
  allRows: BulletinBoardData[];
};

export const Dashboard: NextPage = () => {
  const [open, setOpen] = React.useState(false);
  const [inputText, setInputText] = useState("");
  const [userID, setuserID] = useState("clnz8jzpg00067z3yx42l0w60");
  const [posts, setPosts] = useState<BulletinBoardData[]>([]);

  const getPosts = async () => {
    try {
      const response = await fetch("/api/posts");
      const postsArray: BulletinBoardArray =
        (await response.json()) as BulletinBoardArray;
      const postsReversed = postsArray.allRows.slice().reverse();
      setPosts(postsReversed);
    } catch (error) {
      console.error("Error fetching posts:", error);
    }
  };

  useEffect(() => {
    getPosts();
  }, []);

  const handleButtonClick = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log("<handlebuttonclick></handlebuttonclick>");
    setOpen(false);

    try {
      const res = await fetch("/api/posts", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ userID: userID, message: inputText }),
      });
      const data: string = (await res.json()) as string; // Specify the type
      console.log("Bulletin Post created:", data);
      getPosts();
    } catch (error) {
      console.error("Request failed:", error);
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Counter />

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div>
              <div className="scrollbar h-48 gap-4 overflow-scroll rounded-xl bg-white/10 p-4 text-white">
                <div className="flex space-x-16">
                  <h3 className="text-2xl font-bold">Notice Board</h3>

                  <Dialog.Root open={open} onOpenChange={setOpen}>
                    <Dialog.Trigger asChild>
                      <button className="Button violet">Add New Post</button>
                    </Dialog.Trigger>
                    <Dialog.Portal>
                      <Dialog.Overlay className="DialogOverlay" />
                      <Dialog.Content className="DialogContent">
                        <Dialog.Title className="DialogTitle">
                          Add Bulletin Post
                        </Dialog.Title>
                        <Dialog.Description className="DialogDescription">
                          Add a new bulletin post here. Click save when
                          you&apos;re done.
                        </Dialog.Description>
                        <Dialog.Close asChild>
                          <TestFieldInput />
                        </Dialog.Close>

                        <div className="m-10 h-48 flex-col items-center justify-center">
                          <form onSubmit={handleButtonClick}>
                            <textarea
                              className="h-32 w-full rounded-md border p-2"
                              placeholder="Enter your text..."
                              value={inputText}
                              onChange={(
                                e: React.ChangeEvent<HTMLTextAreaElement>
                              ) => setInputText(e.target.value)}
                            ></textarea>

                            <div
                              style={{
                                display: "flex",
                                marginTop: 25,
                                justifyContent: "flex-end",
                              }}
                            >
                              <button
                                className="Button rounder-r bg-blue-600 p-2 text-white shadow duration-300 hover:bg-blue-700"
                                type="button"
                              >
                                Submit
                              </button>
                            </div>
                            <Dialog.Close asChild>
                              <button className="IconButton" aria-label="Close">
                                <Cross2Icon />
                              </button>
                            </Dialog.Close>
                          </form>
                        </div>
                      </Dialog.Content>
                    </Dialog.Portal>
                  </Dialog.Root>
                </div>

                <ul>
                  {posts.map((post) => (
                    <li key={post.id}>
                      <p className="text-lg">{post.description}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
            {/* <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            ></Link> */}
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="./api/auth/signout"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Log out →</h3>
              <div className="text-lg">Log out from this application!</div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};
